

server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fmarcoss/reto-config-service.git
        default-label: myvalue.yaml
        search-paths:
        - '*service*'


